$(document).ready(function () {
    $('.fourthRecommendSlideBack').after("<div class='subFooterBack'></div>")
    $('.subFooterBack').css({ width: "100%", height: "150px", marginTop: "70px" })

    $(".subFooterBack").append("<div class='subFooter'></div>")
    $(".subFooter").css({ width: "980px", height: "100%", margin: "0 auto" })
    $(".subFooter").append("<div class='subFooterTop'></div>")
    $(".subFooterTop").css({ width: "980px", height: "35px", paddingBottom: "5px", lineHeight: "25px", borderBottom: "3px solid #000" })
    $(".subFooterTop").append("<h2 class='subFooterTopLeft'>서비스 & 혜택</h2>")
    $(".subFooterTopLeft").css({ float: "left", fontSize: "20px" })
    $(".subFooterTop").append("<div class='subFooterTopRight'><a href='#'><h3>공지사항></h3></a><a href='#'>2024년 구정 연휴 배송일정 안내 </a></div>")
    $(".subFooterTopRight").css({ float: "right", fontSize: "11px", fontWeight: "bold", paddingRight: "120px" })
    $(".subFooterTopRight>a").css({ fontSize: "11px", fontWeight: "bold", padding: "10px", color: "#666" })
    $(".subFooterTopRight>a>h3").css({ float: "left", fontSize: "12px", color: "#000" })


    $(".subFooter").append("<div class='subFooterBottom'></div>")
    $(".subFooterBottom").css({ float: "left", width: "980px", height: "110px", paddingTop: "5px" })

    $(".subFooterBottom").append("<ul class='subFooterBottomFirst'>알뜰구매 혜택</ul>")
    $(".subFooterBottomFirst").css({ width: "25%", height: "100%" })
    $(".subFooterBottom").append("<ul class='subFooterBottomSecond'>핵심서비스</ul>")
    $(".subFooterBottomSecond").css({ width: "25%", height: "100%" })
    $(".subFooterBottom").append("<ul class='subFooterBottomThird'>안심배송서비스</ul>")
    $(".subFooterBottomThird").css({ width: "25%", height: "100%" })
    $(".subFooterBottomThird").append("<li><a href='#'>해외주문배송 서비스</a></li>")
    $(".subFooterBottomThird").append("<li><a href='#'>안심번호 서비스</a></ul>")
    $(".subFooterBottomThird>li>a").css({ fontSize: "11px", color: "#666" })
    $(".subFooterBottom").append("<ul class='subFooterBottomFourth'>고객센터</ul>")
    $(".subFooterBottomFourth").css({ width: "25%", height: "100%" })
    $(".subFooterBottomFourth").append("<li>일반문의<span>1577-2555</span></li>")
    $(".subFooterBottomFourth").append("<li>eBook 문의<span>1588-2547</span></li>")
    $(".subFooterBottomFourth>li>span").eq(1).css({ paddingLeft: "45px" })
    $(".subFooterBottomFourth>li>span").css({ paddingLeft: "30px" })
    $(".subFooterBottomFourth").append("<li>월~금 (09:00~18:00), 토요일, 일요일, 공휴일 휴무</li>")
    $(".subFooterBottomFourth>li").css({ fontSize: "10px", color: "#262626" })
    $(".subFooterBottom>ul").css({ float: "left", fontWeight: "bold", fontSize: "14px" })

})